# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '音视频合成Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for 音视频合成Demo
  pod 'FLEX', '~>2.0'

end
